# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-17 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('pais', models.CharField(max_length=150, verbose_name='Pa\xeds')),
            ],
            options={
                'verbose_name': 'Ator',
                'verbose_name_plural': 'Atores',
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('sinopse', models.TextField(verbose_name='Sinopse')),
                ('imagem', models.ImageField(upload_to='filmes/imagens/', verbose_name='Imagem')),
                ('atores', models.ManyToManyField(to='src.Ator', verbose_name='Atores')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'G\xeanero',
                'verbose_name_plural': 'G\xeaneros',
            },
        ),
        migrations.AddField(
            model_name='filme',
            name='generos',
            field=models.ManyToManyField(to='src.Genero', verbose_name='Generos'),
        ),
    ]
