# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ator',
            name='imagem',
            field=models.ImageField(default='atores/imagens/no_image.png', upload_to='atores/imagens/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='imagem',
            field=models.ImageField(default='filmes/imagens/no_image.png', upload_to='filmes/imagens/', verbose_name='Imagem'),
        ),
    ]
